<?php
/**
 * Builds phpMyAdmin-importable SQL for InfinityFree (and other shared hosts) from
 * database/schema.sql and database/seed.sql.
 *
 *   php scripts/build_infinityfree_sql.php
 *
 * Output (database/infinityfree/):
 *   01_schema.sql            all tables; no DROP statements, no views (CREATE VIEW is denied on free hosting)
 *   02_reference_data.sql    catalog data the app needs: settings, programs, strands, subjects,
 *                            curricula, fee templates, scholarships, public announcements
 *   optional_demo_data.sql   fictional demo people/records from seed.sql (shared demo passwords!)
 *
 * The source files are never modified. Re-run this after changing schema.sql or seed.sql.
 */

declare(strict_types=1);

$root = dirname(__DIR__);
$outDir = $root . '/database/infinityfree';
if (!is_dir($outDir) && !mkdir($outDir, 0755, true)) {
    fwrite(STDERR, "Cannot create $outDir\n");
    exit(1);
}

$header = static function (string $title, array $notes): string {
    $lines = [
        '-- ============================================================================',
        '-- Triple T University Enrollment & LMS - ' . $title,
        '-- Generated by scripts/build_infinityfree_sql.php - do not edit by hand.',
    ];
    foreach ($notes as $note) {
        $lines[] = '-- ' . $note;
    }
    $lines[] = '-- ============================================================================';
    $lines[] = '';
    $lines[] = 'SET NAMES utf8mb4;';
    $lines[] = 'SET FOREIGN_KEY_CHECKS = 0;';
    $lines[] = 'SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";';
    $lines[] = '';
    return implode("\n", $lines) . "\n";
};
$footer = "\nSET FOREIGN_KEY_CHECKS = 1;\n";

// ---------------------------------------------------------------------------
// 1. Schema
// ---------------------------------------------------------------------------
$schema = str_replace("\r\n", "\n", (string) file_get_contents($root . '/database/schema.sql'));
preg_match_all('/CREATE TABLE `[a-z0-9_]+` \(.*?\n\)[^;]*;/s', $schema, $m);
$tables = [];
foreach ($m[0] as $create) {
    // Start every table's counter at 1 on a fresh server
    $tables[] = preg_replace('/ AUTO_INCREMENT=\d+/', '', $create);
}
if (count($tables) < 40) {
    fwrite(STDERR, "Unexpectedly found only " . count($tables) . " tables in schema.sql\n");
    exit(1);
}
$viewCount = preg_match_all('/CREATE (?:OR REPLACE )?VIEW/i', $schema);

file_put_contents(
    $outDir . '/01_schema.sql',
    $header('Database Schema (' . count($tables) . ' tables)', [
        'Import FIRST, into an EMPTY database, via phpMyAdmin > Import.',
        'Contains no DROP statements: if a table already exists the import stops instead of overwriting data.',
        "Omitted: {$viewCount} reporting views (CREATE VIEW is not permitted on InfinityFree free hosting;",
        'the application code does not query them).',
    ]) . "\n" . implode("\n\n", $tables) . "\n" . $footer
);

// ---------------------------------------------------------------------------
// 2. Seed split: reference data vs demo data
// ---------------------------------------------------------------------------
$referenceTables = [
    'system_settings', 'announcements',
    'college_programs', 'shs_strands', 'subjects',
    'college_curricula', 'college_curriculum_subjects',
    'shs_curricula', 'shs_curriculum_subjects',
    'fee_templates', 'scholarships',
];
// Sequences initialise themselves on first use, so they are not seeded on production.
$skipTables = ['student_number_sequences', 'receipt_sequences'];

$seed = str_replace("\r\n", "\n", (string) file_get_contents($root . '/database/seed.sql'));
$statements = [];
$current = null;
foreach (explode("\n", $seed) as $line) {
    if ($current === null && preg_match('/^INSERT INTO `([a-z0-9_]+)`/', $line, $tm)) {
        $current = ['table' => $tm[1], 'sql' => ''];
    }
    if ($current !== null) {
        $current['sql'] .= $line . "\n";
        if (preg_match('/\);\s*$/', $line)) {
            $statements[] = $current;
            $current = null;
        }
    }
}
if ($current !== null) {
    fwrite(STDERR, "Unterminated INSERT for table {$current['table']} in seed.sql\n");
    exit(1);
}

$reference = [];
$demo = [];
foreach ($statements as $st) {
    if (in_array($st['table'], $skipTables, true)) {
        continue;
    }
    if (in_array($st['table'], $referenceTables, true)) {
        $reference[] = $st['sql'];
    } else {
        $demo[] = $st['sql'];
    }
}

file_put_contents(
    $outDir . '/02_reference_data.sql',
    $header('Reference / Catalog Data', [
        'Import SECOND, right after 01_schema.sql.',
        'Programs, SHS strands, subjects, curricula, fee templates, scholarships, system settings',
        'and public announcements. Contains no user accounts or personal data.',
        'Review fees, school year and scholarship dates in the admin panel after importing.',
    ]) . "\n" . implode("\n", $reference) . $footer
);

file_put_contents(
    $outDir . '/optional_demo_data.sql',
    $header('OPTIONAL Demo Data (fictional people)', [
        'DO NOT import on a real/public site unless you only want a demo.',
        'Creates demo staff, faculty, applicants and students that ALL share published default passwords',
        '(staff: admin123, students/faculty: password123). Change or deactivate them immediately if used.',
        'Import after 01_schema.sql and 02_reference_data.sql. Referenced upload files are not included.',
    ]) . "\n" . implode("\n", $demo) . $footer
);

printf(
    "Wrote %s\n  01_schema.sql           %d tables (%d views omitted)\n  02_reference_data.sql   %d INSERT statements\n  optional_demo_data.sql  %d INSERT statements\n",
    $outDir,
    count($tables),
    $viewCount,
    count($reference),
    count($demo)
);
