-- ============================================================================
-- Triple T University Enrollment & LMS - Reference / Catalog Data
-- Generated by scripts/build_infinityfree_sql.php - do not edit by hand.
-- Import SECOND, right after 01_schema.sql.
-- Programs, SHS strands, subjects, curricula, fee templates, scholarships, system settings
-- and public announcements. Contains no user accounts or personal data.
-- Review fees, school year and scholarship dates in the admin panel after importing.
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";


INSERT INTO `system_settings` (`id`, `setting_key`, `setting_value`, `created_at`, `updated_at`) VALUES
(1, 'active_school_year', '2026-2027', NOW(), NOW()),
(2, 'enrollment_status', 'open', NOW(), NOW()),
(3, 'college_cost_per_unit', '500.00', NOW(), NOW()),
(4, 'system_name', 'Triple T University Enrollment & LMS', NOW(), NOW()),
(5, 'contact_email', 'admissions@ttu.edu.ph', NOW(), NOW()),
(6, 'active_semester', 'First', NOW(), NOW()),
(7, 'payment_max_concurrency', '100', NOW(), NOW()),
(8, 'payment_session_duration_minutes', '15', NOW(), NOW()),
(9, 'payment_queue_enabled', '1', NOW(), NOW());

INSERT INTO `announcements` (`id`, `badge_label`, `badge_color`, `title`, `content`, `is_active`, `created_at`, `updated_at`) VALUES
(1, 'Admissions', 'primary', 'Academic Year 2026-2027 Enrollment is Now Open', 'Triple T University is officially accepting freshman, transferee, and senior high school applications for the upcoming academic year. Complete your online registration and submit digital requirements today.', 1, NOW(), NOW()),
(2, 'Scholarship', 'success', 'Academic & Athletic Scholarship Grants Open', 'Qualified valedictorians, salutatorians, and varsity athletes are invited to submit their scholarship applications through the student portal before September 30, 2026.', 1, NOW(), NOW()),
(3, 'Registrar', 'info', 'Curriculum Updates & Section Schedules Available', 'New curriculum roadmaps and timetable offerings for College of Computer Studies and Senior High School strands have been published.', 1, NOW(), NOW());

INSERT INTO `college_programs` (`id`, `code`, `name`, `description`, `icon`, `careers`, `custom_tuition`, `is_active`, `created_at`, `updated_at`) VALUES
(1, 'BSIT', 'Bachelor of Science in Information Technology', 'Prepares students in network administration, web systems, database design, and cybersecurity.', 'bi-pc-display', 'Software Engineer, IT Analyst, System Admin', '₱500 / unit (Est. ₱6,000 / sem)', 1, NOW(), NOW()),
(2, 'BSCS', 'Bachelor of Science in Computer Science', 'Focuses on computing theory, algorithm design, software engineering, and artificial intelligence.', 'bi-laptop', 'Data Scientist, Systems Architect, AI Researcher', '₱500 / unit (Est. ₱6,000 / sem)', 1, NOW(), NOW()),
(3, 'BSIS', 'Bachelor of Science in Information Systems', 'Integrates business management with enterprise computing architectures and business analytics.', 'bi-diagram-3', 'Systems Analyst, ERP Consultant, IT Manager', '₱25,000 - ₱30,000 / sem', 1, NOW(), NOW()),
(4, 'BSHM', 'Bachelor of Science in Hospitality Management', 'Professional training in hotel operations, culinary arts, and tourism management.', 'bi-cup-hot', 'Hotel Manager, F&B Director, Event Coordinator', '₱25,000 - ₱30,000 / sem', 1, NOW(), NOW());

INSERT INTO `shs_strands` (`id`, `code`, `name`, `description`, `icon`, `careers`, `custom_tuition`, `is_active`, `created_at`, `updated_at`) VALUES
(1, 'STEM', 'Science, Technology, Engineering, and Mathematics', 'Academic track for engineering, pure sciences, and computing specializations.', 'bi-calculator', 'Engineer, Programmer, Architect', '₱16,500 / sem', 1, NOW(), NOW()),
(2, 'ABM', 'Accountancy, Business, and Management', 'Academic track for entrepreneurship, financial management, and business administration.', 'bi-briefcase', 'Accountant, Entrepreneur, Manager', '₱15,000 - ₱20,000 / sem', 1, NOW(), NOW()),
(3, 'HUMSS', 'Humanities and Social Sciences', 'Academic track for communication arts, law, journalism, and social sciences.', 'bi-chat-square-quote', 'Lawyer, Teacher, Psychologist', '₱15,000 - ₱20,000 / sem', 1, NOW(), NOW()),
(4, 'TVL-ICT', 'Technical-Vocational-Livelihood (ICT Strand)', 'Vocational track in computer programming, animation, and technical drafting.', 'bi-laptop', 'Technician, Web Developer, IT Support', '₱15,000 / sem', 1, NOW(), NOW());

INSERT INTO `subjects` (`id`, `subject_code`, `subject_name`, `units`, `subject_type`, `description`, `education_level`, `status`, `created_at`, `updated_at`) VALUES
(1, 'CC101', 'Introduction to Computing', 3, 'Lecture', 'Fundamental computing principles, binary logic, and digital literacy.', 'College', 1, NOW(), NOW()),
(2, 'CC102', 'Fundamentals of Programming', 3, 'Lecture', 'Procedural problem-solving and structured programming algorithms.', 'College', 1, NOW(), NOW()),
(3, 'MATH101', 'Calculus 1', 3, 'Lecture', 'Limits, derivatives, integrals, and analytical geometry.', 'College', 1, NOW(), NOW()),
(4, 'ENG101', 'Purposive Communication', 3, 'Lecture', 'Writing, speaking, and presenting to different audiences in multimodal contexts.', 'College', 1, NOW(), NOW()),
(5, 'IT101', 'Web Systems and Technologies', 3, 'Lecture', 'Client-side web architecture, HTML5, CSS3 tokens, and JavaScript engines.', 'College', 1, NOW(), NOW()),
(6, 'CS101', 'Data Structures and Algorithms', 3, 'Lecture', 'Stacks, queues, linked lists, trees, graphs, and Big-O efficiency analysis.', 'College', 1, NOW(), NOW()),
(7, 'DB101', 'Database Management Systems', 3, 'Lecture', 'Relational database modeling, ER diagrams, normalization, and SQL optimization.', 'College', 1, NOW(), NOW()),
(8, 'SHS-STEM101', 'Pre-Calculus (STEM)', 4, 'Lecture', 'Trigonometric functions, conic sections, and mathematical induction for Grade 11.', 'SHS', 1, NOW(), NOW()),
(9, 'SHS-GENBIO1', 'General Biology 1', 4, 'Lecture', 'Cellular biology, genetics, and molecular biochemistry for STEM students.', 'SHS', 1, NOW(), NOW()),
(10, 'SHS-ENG01', 'Oral Communication in Context', 3, 'Lecture', 'Development of listening and speaking skills in varied communication situations.', 'SHS', 1, NOW(), NOW()),
(11, 'SHS-PR101', 'Empowerment Technologies (ICT)', 3, 'Lecture', 'ICT fundamentals, digital content creation, and multimedia design for TVL.', 'SHS', 1, NOW(), NOW());

INSERT INTO `college_curricula` (`id`, `program_id`, `curriculum_name`, `version`, `effective_academic_year`, `description`, `status`, `created_at`, `updated_at`) VALUES
(1, 1, 'BSIT 2026 Standard Curriculum', '1.0', '2026-2027', 'Official curriculum blueprint for BS Information Technology.', 'active', NOW(), NOW()),
(2, 2, 'BSCS 2026 Standard Curriculum', '1.0', '2026-2027', 'Official curriculum blueprint for BS Computer Science.', 'active', NOW(), NOW());

INSERT INTO `college_curriculum_subjects` (`id`, `curriculum_id`, `subject_id`, `year_level`, `semester`, `display_order`, `created_at`, `updated_at`) VALUES
(1, 1, 1, '1st Year', 'First', 1, NOW(), NOW()),
(2, 1, 2, '1st Year', 'First', 2, NOW(), NOW()),
(3, 1, 4, '1st Year', 'First', 3, NOW(), NOW()),
(4, 1, 5, '1st Year', 'Second', 1, NOW(), NOW()),
(5, 1, 7, '1st Year', 'Second', 2, NOW(), NOW()),
(6, 2, 1, '1st Year', 'First', 1, NOW(), NOW()),
(7, 2, 2, '1st Year', 'First', 2, NOW(), NOW()),
(8, 2, 3, '1st Year', 'First', 3, NOW(), NOW()),
(9, 2, 6, '1st Year', 'Second', 1, NOW(), NOW());

INSERT INTO `shs_curricula` (`id`, `strand_id`, `curriculum_name`, `version`, `effective_academic_year`, `description`, `status`, `created_at`, `updated_at`) VALUES
(1, 1, 'STEM Grade 11-12 Curriculum', '1.0', '2026-2027', 'DepEd aligned STEM curriculum matrix.', 'active', NOW(), NOW()),
(2, 4, 'TVL-ICT Grade 11-12 Curriculum', '1.0', '2026-2027', 'Vocational ICT track curriculum matrix.', 'active', NOW(), NOW());

INSERT INTO `shs_curriculum_subjects` (`id`, `curriculum_id`, `subject_id`, `grade_level`, `semester`, `created_at`, `updated_at`) VALUES
(1, 1, 8, 'Grade 11', 'First', NOW(), NOW()),
(2, 1, 9, 'Grade 11', 'First', NOW(), NOW()),
(3, 1, 10, 'Grade 11', 'First', NOW(), NOW()),
(4, 2, 10, 'Grade 11', 'First', NOW(), NOW()),
(5, 2, 11, 'Grade 11', 'First', NOW(), NOW());

INSERT INTO `fee_templates` (`id`, `name`, `academic_level`, `grade_level`, `strand`, `semester`, `is_per_unit`, `tuition_fee`, `miscellaneous_fee`, `registration_fee`, `laboratory_fee`, `other_fees`, `total_amount`, `created_at`, `updated_at`) VALUES
(1, 'College BSIT 1st Year (Rate per Unit)', 'College', '1st Year', 'BSIT', 'First', 1, 500.00, 2500.00, 500.00, 2000.00, 1000.00, 6000.00, NOW(), NOW()),
(2, 'College BSCS 1st Year (Rate per Unit)', 'College', '1st Year', 'BSCS', 'First', 1, 500.00, 2500.00, 500.00, 2000.00, 1000.00, 6000.00, NOW(), NOW()),
(3, 'SHS STEM Grade 11 Standard', 'Senior High School', 'Grade 11', 'STEM', 'First', 0, 12000.00, 2000.00, 500.00, 1500.00, 500.00, 16500.00, NOW(), NOW()),
(4, 'SHS TVL Grade 11 Standard', 'Senior High School', 'Grade 11', 'TVL-ICT', 'First', 0, 10000.00, 2000.00, 500.00, 2000.00, 500.00, 15000.00, NOW(), NOW());

INSERT INTO `scholarships` (`id`, `name`, `code`, `category`, `provider`, `program_id`, `year_level`, `min_gwa`, `income_requirement`, `slots`, `tuition_coverage_type`, `tuition_coverage_value`, `misc_coverage_type`, `misc_coverage_value`, `stipend_amount`, `book_allowance`, `description`, `requirements`, `application_start`, `application_end`, `status`, `created_at`, `updated_at`) VALUES
(1, 'Academic Excellence Full Scholarship', 'ACAD-FULL', 'School-Based', 'Triple T University Board', 1, '1st Year', 1.25, NULL, 50, 'percentage', 100.00, 'percentage', 100.00, 5000.00, 3000.00, '100% Tuition and Miscellaneous fee waiver for high-ranking honor graduates.', '1. Certified True Copy of Grades\n2. Certificate of Valedictorian/Salutatorian Rank\n3. Certificate of Good Moral Character', '2026-06-01', '2026-09-30', 'Active', NOW(), NOW()),
(2, 'Athletic Varsity Grant', 'ATH-50', 'School-Based', 'TTU Athletics Council', NULL, 'All', 2.50, NULL, 30, 'percentage', 50.00, 'percentage', 0.00, 2000.00, 0.00, '50% Tuition discount for university varsity players.', '1. Coach Recommendation Letter\n2. Medical Fitness Clearance\n3. Proof of Enrollment', '2026-06-01', '2026-09-30', 'Active', NOW(), NOW()),
(3, 'CHED Tulong Dunong Program', 'CHED-TDP', 'Government', 'Commission on Higher Education (CHED)', NULL, 'All', 2.75, 300000.00, 100, 'fixed', 7500.00, 'fixed', 0.00, 0.00, 0.00, 'Government financial grant providing PHP 7,500 assistance per semester.', '1. Certificate of Indigency\n2. Parents ITR or Certificate of Low Income\n3. Grade 12 Report Card', '2026-06-01', '2026-10-31', 'Active', NOW(), NOW());

SET FOREIGN_KEY_CHECKS = 1;
