-- ============================================================================
-- Triple T University - Remove demo/sample records (fresh start)
-- Hand-written; not generated by scripts/build_infinityfree_sql.php.
--
-- Deletes every application, document record, enrollment, section, payment,
-- assessment, scholarship application/award, clinic record and all LMS content
-- (courses, modules, lessons/materials, assignments, submissions, quizzes,
-- attempts, attendance, announcements, messages), plus activity logs and
-- login-attempt history.
--
-- KEEPS: every user account (including the demo accounts), faculty profiles,
-- faculty availability/specializations, and the school setup from
-- 02_reference_data.sql (programs, strands, curricula, subjects, fees,
-- scholarship programs, homepage announcements, system settings) and the
-- student-number / receipt counters.
--
-- This cannot be undone. Export a backup in phpMyAdmin first.
-- Run in phpMyAdmin: select your database, open the SQL tab, paste, click Go.
-- ============================================================================

SET FOREIGN_KEY_CHECKS = 0;

-- LMS content
DELETE FROM `lms_quiz_answers`;          ALTER TABLE `lms_quiz_answers` AUTO_INCREMENT = 1;
DELETE FROM `lms_quiz_attempts`;         ALTER TABLE `lms_quiz_attempts` AUTO_INCREMENT = 1;
DELETE FROM `lms_question_choices`;      ALTER TABLE `lms_question_choices` AUTO_INCREMENT = 1;
DELETE FROM `lms_questions`;             ALTER TABLE `lms_questions` AUTO_INCREMENT = 1;
DELETE FROM `lms_quizzes`;               ALTER TABLE `lms_quizzes` AUTO_INCREMENT = 1;
DELETE FROM `lms_submissions`;           ALTER TABLE `lms_submissions` AUTO_INCREMENT = 1;
DELETE FROM `lms_assignments`;           ALTER TABLE `lms_assignments` AUTO_INCREMENT = 1;
DELETE FROM `lms_materials`;             ALTER TABLE `lms_materials` AUTO_INCREMENT = 1;
DELETE FROM `lms_modules`;               ALTER TABLE `lms_modules` AUTO_INCREMENT = 1;
DELETE FROM `lms_attendance_records`;    ALTER TABLE `lms_attendance_records` AUTO_INCREMENT = 1;
DELETE FROM `lms_attendance_sessions`;   ALTER TABLE `lms_attendance_sessions` AUTO_INCREMENT = 1;
DELETE FROM `lms_announcements`;         ALTER TABLE `lms_announcements` AUTO_INCREMENT = 1;
DELETE FROM `lms_messages`;              ALTER TABLE `lms_messages` AUTO_INCREMENT = 1;
DELETE FROM `lms_thread_participants`;   ALTER TABLE `lms_thread_participants` AUTO_INCREMENT = 1;
DELETE FROM `lms_threads`;               ALTER TABLE `lms_threads` AUTO_INCREMENT = 1;
DELETE FROM `lms_courses`;               ALTER TABLE `lms_courses` AUTO_INCREMENT = 1;

-- Enrollment, sections and finance
DELETE FROM `college_enrollments`;       ALTER TABLE `college_enrollments` AUTO_INCREMENT = 1;
DELETE FROM `college_section_subjects`;  ALTER TABLE `college_section_subjects` AUTO_INCREMENT = 1;
DELETE FROM `college_sections`;          ALTER TABLE `college_sections` AUTO_INCREMENT = 1;
DELETE FROM `shs_enrollments`;           ALTER TABLE `shs_enrollments` AUTO_INCREMENT = 1;
DELETE FROM `shs_section_subjects`;      ALTER TABLE `shs_section_subjects` AUTO_INCREMENT = 1;
DELETE FROM `shs_sections`;              ALTER TABLE `shs_sections` AUTO_INCREMENT = 1;
DELETE FROM `assessment_items`;          ALTER TABLE `assessment_items` AUTO_INCREMENT = 1;
DELETE FROM `student_assessments`;       ALTER TABLE `student_assessments` AUTO_INCREMENT = 1;
DELETE FROM `payment_sessions`;          ALTER TABLE `payment_sessions` AUTO_INCREMENT = 1;
DELETE FROM `payment_records`;           ALTER TABLE `payment_records` AUTO_INCREMENT = 1;
DELETE FROM `scholarship_recipients`;    ALTER TABLE `scholarship_recipients` AUTO_INCREMENT = 1;
DELETE FROM `scholarship_applications`;  ALTER TABLE `scholarship_applications` AUTO_INCREMENT = 1;

-- Admissions and clinic
DELETE FROM `application_subject_requests`; ALTER TABLE `application_subject_requests` AUTO_INCREMENT = 1;
DELETE FROM `application_documents`;     ALTER TABLE `application_documents` AUTO_INCREMENT = 1;
DELETE FROM `applications`;              ALTER TABLE `applications` AUTO_INCREMENT = 1;
DELETE FROM `health_records`;            ALTER TABLE `health_records` AUTO_INCREMENT = 1;

-- History
DELETE FROM `activity_logs`;             ALTER TABLE `activity_logs` AUTO_INCREMENT = 1;
DELETE FROM `login_attempts`;            ALTER TABLE `login_attempts` AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
