-- ============================================================================
-- Triple T University Enrollment & LMS - Reset to ONE sample enrolled student and ONE LMS class
-- Generated by scripts/build_infinityfree_sql.php - do not edit by hand.
-- For a database that already has the demo accounts (optional_demo_data.sql was imported).
-- Deletes ALL applications, enrollments, payments and LMS content (same as remove_demo_data.sql),
-- keeps every user account, then adds: John Doe (2026-000001) enrolled in BSIT 1-A, and the CC101
-- class taught by Alan Turing with a syllabus, a lesson, an assignment, a quiz and an announcement.
-- Upload the matching files from demo_files/ (see demo_files/README.md). Export a backup first.
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";


-- LMS content
DELETE FROM `lms_material_progress`;     ALTER TABLE `lms_material_progress` AUTO_INCREMENT = 1;
DELETE FROM `lms_quiz_answers`;          ALTER TABLE `lms_quiz_answers` AUTO_INCREMENT = 1;
DELETE FROM `lms_quiz_attempts`;         ALTER TABLE `lms_quiz_attempts` AUTO_INCREMENT = 1;
DELETE FROM `lms_question_choices`;      ALTER TABLE `lms_question_choices` AUTO_INCREMENT = 1;
DELETE FROM `lms_questions`;             ALTER TABLE `lms_questions` AUTO_INCREMENT = 1;
DELETE FROM `lms_quizzes`;               ALTER TABLE `lms_quizzes` AUTO_INCREMENT = 1;
DELETE FROM `lms_submissions`;           ALTER TABLE `lms_submissions` AUTO_INCREMENT = 1;
DELETE FROM `lms_assignments`;           ALTER TABLE `lms_assignments` AUTO_INCREMENT = 1;
DELETE FROM `lms_materials`;             ALTER TABLE `lms_materials` AUTO_INCREMENT = 1;
DELETE FROM `lms_modules`;               ALTER TABLE `lms_modules` AUTO_INCREMENT = 1;
DELETE FROM `lms_attendance_records`;    ALTER TABLE `lms_attendance_records` AUTO_INCREMENT = 1;
DELETE FROM `lms_attendance_sessions`;   ALTER TABLE `lms_attendance_sessions` AUTO_INCREMENT = 1;
DELETE FROM `lms_announcements`;         ALTER TABLE `lms_announcements` AUTO_INCREMENT = 1;
DELETE FROM `lms_messages`;              ALTER TABLE `lms_messages` AUTO_INCREMENT = 1;
DELETE FROM `lms_thread_participants`;   ALTER TABLE `lms_thread_participants` AUTO_INCREMENT = 1;
DELETE FROM `lms_threads`;               ALTER TABLE `lms_threads` AUTO_INCREMENT = 1;
DELETE FROM `lms_courses`;               ALTER TABLE `lms_courses` AUTO_INCREMENT = 1;

-- Enrollment, sections and finance
DELETE FROM `college_enrollments`;       ALTER TABLE `college_enrollments` AUTO_INCREMENT = 1;
DELETE FROM `college_section_subjects`;  ALTER TABLE `college_section_subjects` AUTO_INCREMENT = 1;
DELETE FROM `college_sections`;          ALTER TABLE `college_sections` AUTO_INCREMENT = 1;
DELETE FROM `shs_enrollments`;           ALTER TABLE `shs_enrollments` AUTO_INCREMENT = 1;
DELETE FROM `shs_section_subjects`;      ALTER TABLE `shs_section_subjects` AUTO_INCREMENT = 1;
DELETE FROM `shs_sections`;              ALTER TABLE `shs_sections` AUTO_INCREMENT = 1;
DELETE FROM `assessment_items`;          ALTER TABLE `assessment_items` AUTO_INCREMENT = 1;
DELETE FROM `student_assessments`;       ALTER TABLE `student_assessments` AUTO_INCREMENT = 1;
DELETE FROM `payment_sessions`;          ALTER TABLE `payment_sessions` AUTO_INCREMENT = 1;
DELETE FROM `payment_records`;           ALTER TABLE `payment_records` AUTO_INCREMENT = 1;
DELETE FROM `scholarship_recipients`;    ALTER TABLE `scholarship_recipients` AUTO_INCREMENT = 1;
DELETE FROM `scholarship_applications`;  ALTER TABLE `scholarship_applications` AUTO_INCREMENT = 1;

-- Admissions and clinic
DELETE FROM `application_subject_requests`; ALTER TABLE `application_subject_requests` AUTO_INCREMENT = 1;
DELETE FROM `application_documents`;     ALTER TABLE `application_documents` AUTO_INCREMENT = 1;
DELETE FROM `applications`;              ALTER TABLE `applications` AUTO_INCREMENT = 1;
DELETE FROM `health_records`;            ALTER TABLE `health_records` AUTO_INCREMENT = 1;

-- History
DELETE FROM `activity_logs`;             ALTER TABLE `activity_logs` AUTO_INCREMENT = 1;
DELETE FROM `login_attempts`;            ALTER TABLE `login_attempts` AUTO_INCREMENT = 1;

INSERT INTO `college_sections` (`id`, `section_code`, `program_id`, `curriculum_id`, `academic_year`, `year_level`, `semester`, `capacity`, `schedule_type`, `adviser`, `status`, `created_at`, `updated_at`) VALUES
(1, 'BSIT 1-A', 1, 1, '2026-2027', '1st Year', 'First', 40, 'Morning', 'Alan Turing', 1, NOW(), NOW());

INSERT INTO `college_section_subjects` (`id`, `college_section_id`, `subject_id`, `capacity`, `day`, `start_time`, `end_time`, `room`, `faculty_user_id`, `instructor`, `delivery_mode`, `created_at`, `updated_at`) VALUES
(1, 1, 1, 40, 'MWF', '08:00:00', '09:00:00', 'Lab 101', 8, 'Alan Turing', 'Face-to-Face', NOW(), NOW());

INSERT INTO `applications` (`id`, `user_id`, `reference_number`, `academic_level`, `grade_level`, `school_year`, `semester`, `student_type`, `strand`, `nstp`, `section_id`, `college_curriculum_id`, `status`, `document_submission_method`, `admin_feedback`, `internal_notes`, `contact_number`, `telephone_number`, `birth_date`, `gender`, `civil_status`, `nationality`, `religion`, `place_of_birth`, `address_house_number`, `address_street`, `address_barangay`, `address_city`, `address_province`, `address_zip`, `address`, `guardian_name`, `guardian_relationship`, `guardian_contact`, `previous_school`, `previous_school_year`, `previous_school_type`, `lrn`, `emergency_name`, `emergency_relationship`, `emergency_contact`, `created_at`, `updated_at`) VALUES
(1, 11, 'APP-2026-000001', 'College', '1st Year', '2026-2027', 'First', 'Regular', 'BSIT', 'CWTS', 1, 1, 'enrolled', 'online', 'Application verified and enrollment confirmed.', 'Honors graduate from Manila Science HS.', '09171234567', '0281234567', '2007-05-15', 'Male', 'Single', 'Filipino', 'Roman Catholic', 'Manila', '123', 'Mabini Street', 'Barangay 659', 'Manila', 'Metro Manila', '1000', '123 Mabini Street, Barangay 659, Manila, Metro Manila', 'Robert Doe', 'Father', '09179876543', 'Manila Science High School', '2025-2026', 'Public', '123456789012', 'Robert Doe', 'Father', '09179876543', NOW(), NOW());

INSERT INTO `health_records` (`id`, `user_id`, `application_id`, `height`, `weight`, `blood_type`, `has_allergies`, `has_asthma`, `has_diabetes`, `has_hypertension`, `has_heart_disease`, `has_physical_disability`, `has_existing_condition`, `has_previous_surgery`, `has_maintenance_medication`, `has_hospitalized`, `medical_conditions`, `allergies_details`, `current_medications`, `other_notes`, `emergency_name`, `emergency_relationship`, `emergency_contact`, `status`, `admin_remarks`, `created_at`, `updated_at`) VALUES
(1, 11, 1, '175 cm', '68 kg', 'O+', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'None', 'None', 'None', 'Fit for all university and physical education activities.', 'Robert Doe', 'Father', '09179876543', 'verified', 'Medically cleared for academic term.', NOW(), NOW());

INSERT INTO `application_documents` (`id`, `application_id`, `document_name`, `file_path`, `status`, `feedback`, `created_at`, `updated_at`) VALUES
(1, 1, 'PSA Birth Certificate', 'john_doe_psa_birth_certificate.pdf', 'verified', 'Original PSA verified.', NOW(), NOW()),
(2, 1, 'Form 138', 'john_doe_form_138.pdf', 'verified', 'General average 94.8 verified.', NOW(), NOW()),
(3, 1, 'Good Moral Certificate', 'john_doe_good_moral_certificate.pdf', 'verified', 'Verified.', NOW(), NOW()),
(4, 1, '2x2 Picture', 'john_doe_2x2_picture.jpg', 'verified', 'Compliant ID photo.', NOW(), NOW());

INSERT INTO `college_enrollments` (`id`, `application_id`, `subject_id`, `college_section_id`, `created_at`, `updated_at`) VALUES
(1, 1, 1, 1, NOW(), NOW());

INSERT INTO `student_assessments` (`id`, `user_id`, `application_id`, `fee_template_id`, `scholarship_id`, `tuition_fee`, `miscellaneous_fee`, `registration_fee`, `laboratory_fee`, `other_fees`, `total_amount`, `discount_amount`, `net_amount`, `total_paid`, `payment_status`, `created_at`, `updated_at`) VALUES
(1, 11, 1, 1, NULL, 1500.00, 2500.00, 500.00, 2000.00, 1000.00, 7500.00, 0.00, 7500.00, 7500.00, 'paid', NOW(), NOW());

INSERT INTO `payment_records` (`id`, `assessment_id`, `user_id`, `cashier_id`, `amount`, `payment_date`, `payment_method`, `receipt_number`, `reference_number`, `proof_image`, `status`, `remarks`, `created_at`, `updated_at`) VALUES
(1, 1, 11, 4, 7500.00, CURDATE(), 'GCash', 'REC-20260825-0001', 'GCASH-SAMPLE-0001', 'john_doe_payment_proof.jpg', 'verified', 'Full payment verified for enrollment finalization.', NOW(), NOW());

INSERT INTO `lms_courses` (`id`, `academic_level`, `academic_section_id`, `subject_id`, `faculty_user_id`, `status`, `created_at`, `updated_at`) VALUES
(1, 'College', 1, 1, 8, 'active', NOW(), NOW());

INSERT INTO `lms_modules` (`id`, `lms_course_id`, `title`, `description`, `display_order`, `status`, `created_at`, `updated_at`) VALUES
(1, 1, 'Module 1: Introduction to Computers', 'What a computer is, its basic operations, and number systems.', 1, 'published', NOW(), NOW());

INSERT INTO `lms_materials` (`id`, `lms_module_id`, `file_name`, `file_path`, `mime_type`, `file_size`, `created_at`) VALUES
(1, 1, 'CC101 Course Syllabus 2026-2027', 'materials/cc101_syllabus.pdf', 'application/pdf', 3186, NOW()),
(2, 1, 'Lesson 1 - What Is a Computer (slides)', 'materials/cc101_lesson1_what_is_a_computer.pptx', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 32204, NOW());

INSERT INTO `lms_assignments` (`id`, `lms_course_id`, `lms_module_id`, `title`, `description`, `due_date`, `max_score`, `status`, `created_at`, `updated_at`) VALUES
(1, 1, 1, 'Assignment 1: Number Systems Conversion', 'Convert 13, 45, 100 and 255 to binary, octal and hexadecimal. Show your solution for 45 and submit one PDF.', DATE_ADD(NOW(), INTERVAL 7 DAY), 100, 'published', NOW(), NOW());

INSERT INTO `lms_quizzes` (`id`, `lms_course_id`, `title`, `description`, `time_limit`, `max_attempts`, `passing_score`, `start_date`, `end_date`, `status`, `created_at`, `updated_at`) VALUES
(1, 1, 'Quiz 1: Computer Basics', 'Checks Lesson 1: computer operations, memory and binary.', 20, 1, 75.00, NOW(), DATE_ADD(NOW(), INTERVAL 10 DAY), 'published', NOW(), NOW());

INSERT INTO `lms_questions` (`id`, `lms_quiz_id`, `question_text`, `question_type`, `points`, `display_order`, `created_at`) VALUES
(1, 1, 'Which part of the computer performs calculations and logical decisions?', 'multiple_choice', 5.00, 1, NOW()),
(2, 1, 'RAM keeps its contents when the computer is turned off.', 'true_false', 5.00, 2, NOW());

INSERT INTO `lms_question_choices` (`id`, `lms_question_id`, `choice_text`, `is_correct`, `display_order`) VALUES
(1, 1, 'CPU', 1, 1),
(2, 1, 'Monitor', 0, 2),
(3, 1, 'Keyboard', 0, 3),
(4, 1, 'Printer', 0, 4),
(5, 2, 'True', 0, 1),
(6, 2, 'False', 1, 2);

INSERT INTO `lms_announcements` (`id`, `lms_course_id`, `author_user_id`, `title`, `content`, `status`, `published_at`, `expires_at`, `created_at`, `updated_at`) VALUES
(1, 1, 8, 'Welcome to CC101 Introduction to Computing!', 'Please download the syllabus and the Lesson 1 slides from Module 1 before our next meeting.', 'published', NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), NOW(), NOW());

SET FOREIGN_KEY_CHECKS = 1;
